<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>easymp3gain_128x128.ico</ApplicationIcon>
	<Title>FuzzCast ReplayGain</Title>
    <Version>1.0.$([System.DateTime]::UtcNow.AddHours(3).ToString("yy"))$([System.DateTime]::UtcNow.AddHours(3).DayOfYear.ToString("000")).$([System.DateTime]::UtcNow.AddHours(3).ToString("HHmm"))</Version>
  
  <AssemblyVersion>1.0.$([System.DateTime]::UtcNow.AddHours(3).ToString("yy"))$([System.DateTime]::UtcNow.AddHours(3).DayOfYear.ToString("000")).$([System.DateTime]::UtcNow.AddHours(3).ToString("HHmm"))</AssemblyVersion>
  
  <InformationalVersion>1.0 built on $([System.DateTime]::UtcNow.AddHours(3).ToString("yyyy-MM-dd HH:mm")) MSK</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <ItemGroup>
    <Content Include="easymp3gain_128x128.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Bass.Net">
      <HintPath>..\FuzzCast.Source\Bass.Net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="bass.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="decoders\bassopus.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="decoders\bass_aac.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
